alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: pdf.booky.kids
    type: PRIMARY
ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
maintenance: {}
name: pdf-booky-kids
region: nyc1
services:
  - dockerfile_path: /Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: gkutiel/tikzsvg
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    name: web
    source_dir: /
